# Generated by Django 2.2.17 on 2020-12-01 15:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('employees', django.db.models.manager.Manager()),
            ],
        ),
    ]
