# Generated by Django 2.2.17 on 2020-12-02 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201201_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(default='clients/default.png', null=True, upload_to='clients/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=40)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to='website.Client')),
                ('image', models.ImageField(default='testimonials/default.jpg', null=True, upload_to='testimonials/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('testimonial_comment', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
