# Generated by Django 2.2.17 on 2020-12-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_project_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='website.Tag'),
        ),
    ]
