# Generated by Django 3.1.4 on 2020-12-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_auto_20201202_2019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('clients', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='testimonial',
            managers=[
                ('testimonials', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_categorys', to='website.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects_tags', to='website.Tag'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='services/default.jpg', null=True, upload_to='services/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_authors', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_categorys', to='website.category')),
                ('tags', models.ManyToManyField(related_name='services_tags', to='website.Tag')),
            ],
            options={
                'ordering': ['category', 'service_name'],
            },
            managers=[
                ('services', django.db.models.manager.Manager()),
            ],
        ),
    ]
