# Generated by Django 3.1.4 on 2020-12-03 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201203_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_item', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='tom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='tom', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='website.jobtitle'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='testimonials', serialize=False, to='website.client'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('budget', models.CharField(choices=[('500-1000', '$500 - $1000'), ('1000-4000', '$1000 - $4000'), ('4000-8000', '$4000 - $8000'), ('undecided', 'undecided')], default='undecided', max_length=16)),
                ('start_time', models.CharField(choices=[('asap', 'ASAP'), ('1-2', '1-2 weeks'), ('2-4', '2-4 weeks'), ('4plus', '4+ weeks')], default='asap', max_length=16)),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_clients', to='website.client')),
                ('services', models.ManyToManyField(related_name='quotes_services', to='website.Service')),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('period', models.CharField(choices=[('per month', 'per month'), ('per year', 'per year')], default='per month', max_length=10)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('package_items', models.ManyToManyField(related_name='package_items', to='website.PackageItem')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
