# Generated by Django 3.1.4 on 2020-12-04 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201203_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_clients', to='website.client')),
            ],
            options={
                'ordering': ['client', '-status', 'submitted'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_name', models.CharField(max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'ordering': ['tax_rate_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-status', 'submitted']},
        ),
        migrations.AlterModelManagers(
            name='package',
            managers=[
                ('packages', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='packageitem',
            managers=[
                ('package_items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='quote',
            managers=[
                ('quotes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes_clients', to='website.client'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_orders', to='website.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items_packages', to='website.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='tax_rate_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='packages_tax_rate_names', to='website.taxrate'),
            preserve_default=False,
        ),
    ]
