# Generated by Django 3.1.4 on 2020-12-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20201204_1132'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
            ],
        ),
    ]
