# Generated by Django 3.1.4 on 2020-12-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201204_1328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testimonial',
            managers=[
            ],
        ),
    ]
