# Generated by Django 3.1.4 on 2020-12-04 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_auto_20201204_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='posts/default.jpg', null=True, upload_to='posts/')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_authors', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_categorys', to='website.category')),
                ('tags', models.ManyToManyField(related_name='posts_tags', to='website.Tag')),
            ],
            options={
                'ordering': ['-published'],
            },
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
    ]
