# Generated by Django 3.1.4 on 2020-12-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='show_website',
            field=models.BooleanField(default=False),
        ),
    ]
