# Generated by Django 3.1.4 on 2020-12-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_client_show_website'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
