# Generated by Django 3.1.4 on 2020-12-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20201207_1247'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='package',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='packageitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='service',
            managers=[
            ],
        ),
    ]
