# Generated by Django 3.1.4 on 2020-12-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20201209_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects_clients', to='website.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
