# Generated by Django 3.1.4 on 2020-12-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20201231_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_top_package',
            field=models.BooleanField(default=False),
        ),
    ]
